# Generated by Django 5.2.6 on 2026-03-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mob',
            field=models.CharField(max_length=13),
        ),
    ]
