# Generated by Django 5.2.6 on 2026-01-13 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('mob', models.CharField(max_length=10)),
                ('add', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=6)),
                ('total_price', models.PositiveIntegerField()),
                ('payment_type', models.CharField(max_length=50)),
                ('payment_id', models.CharField(max_length=100)),
                ('dt', models.DateTimeField(auto_now=True)),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.registration')),
            ],
        ),
    ]
