# Generated by Django 5.2.6 on 2026-01-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.PositiveIntegerField(verbose_name=10),
        ),
    ]
